/**
 * GENERATED by `npm run og-card`. Do not edit by hand.
 *
 * A content hash of the two built cards, appended to the OG image URL as `?v=`.
 * WhatsApp caches a preview image by URL, so a rebuilt card at the same path is
 * not re-fetched — the fix ships and the chat keeps showing the old picture,
 * with nothing to indicate why. The hash changes only when the pixels do, so a
 * rebuild that changes nothing costs no cache.
 */
export const OG_CARD_VERSION = 'ea8df811aa56a51b'
