-- ---------------------------------------------------------------------------
-- 019 — a running number for guest photos (docs/wedding-photos-PRD.md §5)
--
-- Drive file names become "<name> · <number>.jpg", or "<number>.jpg" when the
-- guest left no name. The number is this row's, so it must exist BEFORE the
-- upload: the route reserves a row, uploads under the name, then attaches the
-- Drive file id. Hence drive_file_id may be null for the few seconds between.
--
-- Adding an identity column numbers the existing rows too. Re-runnable.
-- ---------------------------------------------------------------------------

alter table wedding_photos
  add column if not exists photo_number bigint generated by default as identity;

alter table wedding_photos drop constraint if exists wedding_photos_photo_number_key;
alter table wedding_photos add constraint wedding_photos_photo_number_key unique (photo_number);

-- Null only while a reserved photo is still uploading (or if it failed and
-- the route couldn't clean up). The counter and stats ignore such rows.
alter table wedding_photos alter column drive_file_id drop not null;

-- Verify:
--   select photo_number, drive_file_id is not null as uploaded
--   from wedding_photos order by photo_number;
